# my attempt at writting a game after 6 months of no coding
import time
print('hello')
time.sleep(2)
print('...')
time.sleep(2)
print('i am an old god')
time.sleep(2)
print('...')
time.sleep(2)
print('cough')
time.sleep(2)
print('...')
time.sleep(2)
print("one that is about to die")
time.sleep(2)
print("...")
time.sleep(2)
print('i am the moongazer')
time.sleep(2)
print('...')
time.sleep(2)
print('the guardian of this land')
time.sleep(2)
print('...')
time.sleep(2)
print('but')
time.sleep(2)
print('...')
time.sleep(2)
print('my powers grow weak')
time.sleep(2)
print('...')
time.sleep(2)
print('for the monsters stir')
time.sleep(2)
print('...')
time.sleep(2)
print('terrible')
time.sleep(2)
print("...")
time.sleep(2)
print('terrible monsters')
time.sleep(2)
print('...')
time.sleep(2)
print('cough')
time.sleep(2)
print('...')
time.sleep(2)
name=input("young child what is your name?")
time.sleep(2)
print('...')
time.sleep(2)
print('hmm')
time.sleep(2)
print("...")
time.sleep(2)
print(name)
time.sleep(2)
print("...")
time.sleep(2)
print('thats a good name')
time.sleep(2)
print('...')
time.sleep(2)
age=int(input("how old are you my child?"))
time.sleep(2)
print("...")
if age>=18:
    time.sleep(2)
    print("you are a old one " +name )
    time.sleep(2)
    print("...")
    time.sleep(2)
    print('older than i expected')
    time.sleep(2)
    print("...")
    time.sleep(2)
    print('you will do well')
    time.sleep(2)
    print('...')
else:
    time.sleep(2)
    print("you are a young one " +name )
    time.sleep(2)
    print("...")
    time.sleep(2)
    print('and you have much to learn')
    time.sleep(2)
    print("...")
    time.sleep(2)
    print('cough')
    time.sleep(2)
    print("...")
    time.sleep(2)
    print('but i have faith in you')
    time.sleep(2)
    print("...")
    time.sleep(2)
    print("however")
    time.sleep(2)
    print("...")
    time.sleep(2)
    print("for now you must choose a path")
    time.sleep(2)
    print("...")
    time.sleep(2)
    print('if you do not you will be doomed')
    time.sleep(2)
    print("...")         
if age>= 18:
    time.sleep(2)
    print('you are wise and should be able to make your own decisions')
    time.sleep(2)
else:
    time.sleep(2)
    print('you are young and naieve i pray for your safe passage!')
    time.sleep(2)
print("...")
time.sleep(2)
d=input('there are two options left or right, choose the right path!')
time.sleep(2)
print('...')
if d== "left":
    time.sleep(2)
    print("...")
    time.sleep(2)
    print('left')
    time.sleep(2)
    print("...")
    time.sleep(2)
    print('left is a good direction to follow')
    time.sleep(2)
    print("...")
    time.sleep(2)
    print('i am glad you survived')
    time.sleep(2)
    print("...")
    time.sleep(2)
    print('onwards')
else:
    print('right')
    time.sleep(2)
    print("...")
    time.sleep(2)
    print('i used to think it was the right way to go')
    time.sleep(2)
    print("...")
    time.sleep(2)
    print('you')
    time.sleep(2)
    print("...")
    time.sleep(2)
    print('you were my hero')
    time.sleep(2)
    print("...")
    time.sleep(2)
    print('but for now you are doomed')
    time.sleep(2)
    print("...")
